/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/auth/enrolment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generates a TOTP secret and returns it once. Refused once one is confirmed. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlatformEnrolmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformEnrolment"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/enrolment/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Proves the secret reached an authenticator, and signs the operator in. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlatformSignInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformTokens"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signs in with a password and a code. No refresh handle is issued. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlatformSignInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformTokens"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/break-glass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The break-glass trail across every studio. How operators are audited. */
        get: {
            parameters: {
                query?: {
                    limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupportAuditEvent"][];
                    };
                };
                /** @description No token, an expired one, a revoked session, or a stale permission version. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The operator behind the token, and what they may do. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformOperatorResponse"];
                    };
                };
                /** @description No token, an expired one, a revoked session, or a stale permission version. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations/{organizationId}/break-glass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Records the access, then reads one studio's metadata read-only. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BreakGlassRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupportOrganizationSnapshot"];
                    };
                };
                /** @description No token, an expired one, a revoked session, or a stale permission version. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Changes a password, sparing the calling session. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No token, an expired one, a revoked session, or a stale permission version. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts a password reset. Answers 202 whether or not the address exists. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accepts an invitation. Issues a session only for a new account. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptInvitationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AcceptInvitationResponse"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What an invitation is for, before anybody types anything. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvitationPreview"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signs in with a password. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticationResponse"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ends the current session and clears the refresh cookie. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchanges a refresh handle for a new pair. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticationResponse"];
                    };
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a studio and its owner. Answers 202 either way. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-sends a verification link. Answers 202 for an unknown address too. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendVerificationRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sets a new password from a reset link, revoking every session. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirms an address, which is what unblocks first login. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyEmailRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in caller, their studio, and what they may do. */
        get: operations["GetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/deletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Requests deletion of the organization, starting the recovery window. */
        post: operations["RequestOrganizationDeletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Requests an export of the organization's data (KVKK/GDPR). */
        post: operations["RequestOrganizationExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invitations that have neither been accepted nor withdrawn. */
        get: operations["ListPendingInvitations"];
        put?: never;
        /** Invites somebody onto the roster and mails them a link. */
        post: operations["InviteStaffMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Withdraws an invitation and removes the roster row it created. */
        delete: operations["RevokeInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/invitations/{invitationId}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issues a fresh link, invalidating the previous one. */
        post: operations["ResendInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInvitationRequest: {
            /** @description Required on the new-account path. */
            acceptedKvkkNotice: boolean;
            /** @description Web or native, deciding where the refresh handle goes. */
            clientKind?: components["schemas"]["SessionClientKind"];
            /** @description Their name, as they want it shown. */
            fullName: string;
            /** @description Used only when the invited address has no account yet. */
            password: string;
            /** @description The handle from the invitation link. */
            token: string;
        };
        AcceptInvitationResponse: {
            authentication: null | components["schemas"]["AuthenticationResponse"];
            /** @description The studio they joined. */
            organizationName: string;
            /** @description Whether a new account was created and signed in, or an existing one was linked to the roster. */
            outcome: components["schemas"]["InvitationAcceptance"];
        };
        /**
         * @description What kind of thing happened. Stored as a string, so adding one is a code change with no
         *     migration and reading the table needs no lookup.
         * @enum {unknown}
         */
        AuditAction: "Created" | "Updated" | "Deleted" | "Invited" | "PermissionChanged" | "ConnectionChanged" | "ComplianceRequested" | "PlatformAction" | "BreakGlassOpened";
        /** @description One audit row, as another module or the API may read it. */
        AuditEventSummary: {
            /** @description What kind of thing happened. */
            action: components["schemas"]["AuditAction"];
            /**
             * Format: uuid
             * @description Who. Null for a platform operator, who is on no roster — see ActorUserId.
             */
            actorStaffMemberId: null | string;
            /**
             * Format: uuid
             * @description The account behind the actor. Present even when the staff member id is not, which is how a
             *     platform operator's actions are attributable at all.
             */
            actorUserId: null | string;
            /**
             * Format: uuid
             * @description The row.
             */
            id: string;
            /** @description Scalars describing the change. Never content (ADR-0057's rule). */
            metadata: {
                [key: string]: string;
            };
            /**
             * Format: date-time
             * @description When. Also the partition key, so it is never null and never updated.
             */
            occurredAt: string;
            /**
             * Format: uuid
             * @description Which row, when the action named one.
             */
            resourceId: null | string;
            /** @description The table or aggregate, in `schema.table` form. */
            resourceKind: string;
            /** @description Short machine-readable description from a closed set. */
            summary: string;
        };
        AuthenticationResponse: {
            /** @description Bearer token for the API. */
            accessToken: string;
            /**
             * Format: date-time
             * @description When it stops working.
             */
            accessTokenExpiresAt: string;
            /**
             * Format: uuid
             * @description The studio the session is acting in.
             */
            organizationId: string;
            /**
             * @description Null for web clients, whose handle went into a `HttpOnly` cookie the response body must
             *     not duplicate — a handle in the body is a handle in script's reach, which is exactly what the
             *     cookie flag was for.
             */
            refreshHandle: null | string;
            /**
             * Format: uuid
             * @description The caller's roster row.
             */
            staffMemberId: string;
        };
        /** @description Opening break-glass access. */
        BreakGlassRequest: {
            /**
             * @description Why, in the operator's own words. CLAUDE.md §6 requires a reason; it is stored in the audit
             *     row's metadata rather than its summary, because the summary is a closed vocabulary the trail is
             *     queried by and free text there would make "how often is break-glass used" unanswerable.
             */
            reason: string;
        };
        ChangePasswordRequest: {
            /** @description Proof the caller is the account holder rather than a stolen access token. */
            currentPassword: string;
            /** @description The replacement. Checked against the policy. */
            newPassword: string;
        };
        /** @enum {unknown} */
        DayOfWeek: "Sunday" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday";
        ForgotPasswordRequest: {
            /** @description The address to send a reset link to, if it has an account. */
            email: string;
        };
        /**
         * @description How an acceptance ended.
         * @enum {unknown}
         */
        InvitationAcceptance: "SignedIn" | "AccountLinked";
        /** @description What the acceptance screen renders before anybody types anything. */
        InvitationPreview: {
            /** @description The invited address. Fixed; accepting cannot change it. */
            email: string;
            /**
             * Format: date-time
             * @description When the link stops working.
             */
            expiresAt: string;
            /** @description What the inviter typed. Editable — it is the invitee's name. */
            fullName: string;
            /** @description The studio they are joining. */
            organizationName: string;
            /** @description What they are being invited as. */
            role: components["schemas"]["StaffRole"];
        };
        /** @description An invitation, <b>without</b> its token. */
        InvitationResponse: {
            email: string;
            /** Format: date-time */
            expiresAt: string;
            fullName: string;
            /** Format: uuid */
            invitationId: string;
            role: components["schemas"]["StaffRole"];
            /** Format: uuid */
            staffMemberId: string;
        };
        InviteStaffMemberBody: {
            /** @description Where the invitation goes, and their future login identifier. */
            email: string;
            /** @description Their name, as the inviter types it. The invitee may correct it. */
            fullName: string;
            /** @description Optional. */
            phoneNumber?: null | string;
            /** @description What they are being invited as. */
            role: components["schemas"]["StaffRole"];
        };
        LoginRequest: {
            /** @description Web or native. */
            clientKind?: components["schemas"]["SessionClientKind"];
            /** @description The account. */
            email: string;
            /** @description Their password. */
            password: string;
        };
        MeNavigationEntry: {
            /** @description The nav id the panel already uses, kept identical so migrating is a data change. */
            id: string;
            /** @description The Expo Router path. */
            route: string;
        };
        MeOrganization: {
            /** @description ISO 4217. */
            currency: string;
            /**
             * Format: uuid
             * @description The tenant boundary.
             */
            id: string;
            /** @description BCP 47, for formatting the client cannot infer from the device. */
            locale: string;
            /** @description The single source of the studio name the panel duplicates across three files. */
            name: string;
            /**
             * @description Load-bearing. "Today's sessions" and "revenue this month" are organization-local questions, and
             *     the panel currently answers them from the device clock — so two staff members in different
             *     zones disagree about what day it is.
             */
            timeZoneId: string;
            /** @description First day of the week for calendar rendering. */
            weekStartDay: components["schemas"]["DayOfWeek"];
        };
        MeResponse: {
            /**
             * @description The screens this caller reaches, in sidebar order. Server-owned, so the panel stops keeping its
             *     own copy of the role-to-screen map.
             */
            navigation: components["schemas"]["MeNavigationEntry"][];
            /** @description The studio the session is acting in. */
            organization: components["schemas"]["MeOrganization"];
            /**
             * Format: int32
             * @description What the server currently holds. A client comparing this against its token's `pv` can
             *     refresh before a request fails, rather than after.
             */
            permissionVersion: number | string;
            /**
             * @description Permission string → scope, containing only what the caller holds. Absence is how something is
             *     not granted; there are no `"None"` entries.
             */
            permissions: {
                [key: string]: components["schemas"]["PermissionScope"];
            };
            /** @description The caller's roster row — the assignment key (ADR-0016). */
            staffMember: components["schemas"]["MeStaffMember"];
            /** @description The account. */
            user: components["schemas"]["MeUser"];
        };
        MeStaffMember: {
            /** @description Display name on the roster. */
            fullName: string;
            /**
             * Format: uuid
             * @description The roster row — the assignment key (ADR-0016), not the account id.
             */
            id: string;
            /** @description Their role in this studio. */
            role: components["schemas"]["StaffRole"];
            /** @description Whether they may act. */
            status: components["schemas"]["StaffStatus"];
        };
        MeUser: {
            /** @description As the person typed it. */
            email: string;
            /** @description Display name. */
            fullName: string;
            /**
             * Format: uuid
             * @description The account.
             */
            id: string;
            /**
             * @description False is unreachable here — the sign-in path refuses first — but it is reported rather than
             *     assumed, because that is a property of the account and not of this endpoint's expectations.
             */
            isEmailVerified: boolean;
        };
        /** @description An invitation that has neither been accepted nor withdrawn. */
        PendingInvitation: {
            /**
             * Format: date-time
             * @description When it was sent.
             */
            createdAt: string;
            /** @description Where the invitation went. */
            email: string;
            /**
             * Format: date-time
             * @description When the token stops working.
             */
            expiresAt: string;
            /** @description The invitee's name, as the inviter typed it. */
            fullName: string;
            /**
             * Format: uuid
             * @description The invitation row.
             */
            id: string;
            /**
             * @description Derived, never stored. A stored flag would be wrong from the moment it was written until
             *     something remembered to update it — the same mistake the panel makes with
             *     `renewalDaysLeft`.
             */
            isExpired: boolean;
            /** @description What they were invited as. */
            role: components["schemas"]["StaffRole"];
            /**
             * Format: uuid
             * @description The roster row it will activate.
             */
            staffMemberId: string;
        };
        /**
         * @description How widely a granted permission reaches within the caller's organization.
         * @enum {unknown}
         */
        PermissionScope: "None" | "Own" | "All";
        /** @description A freshly generated TOTP secret, shown exactly once. */
        PlatformEnrolment: {
            /** @description The `otpauth://` URI an authenticator app scans. */
            enrolmentUri: string;
            /** @description Base32, for an operator typing it in by hand. */
            secret: string;
        };
        /** @description Starting TOTP enrolment. Password only — the code does not exist yet. */
        PlatformEnrolmentRequest: {
            /** @description The operator's account address. */
            email: string;
            /** @description Their account password. */
            password: string;
        };
        /** @description Who the caller is on the platform surface. */
        PlatformOperatorResponse: {
            /** @description Their address. */
            email: string;
            /** @description Their name. */
            fullName: string;
            /**
             * Format: uuid
             * @description The grant this token acts under.
             */
            operatorId: string;
            /** @description What they may do. Advisory — every one is re-checked on the request that uses it. */
            permissions: string[];
        };
        /** @description Signing in, or confirming enrolment. Both need all three. */
        PlatformSignInRequest: {
            /** @description The operator's account address. */
            email: string;
            /** @description Their account password. */
            password: string;
            /** @description Six digits from their authenticator. */
            totpCode: string;
        };
        /** @description What a successful platform sign-in hands back. */
        PlatformTokens: {
            /** @description Short-lived bearer token on the `fitbase-admin` audience. */
            accessToken: string;
            /**
             * Format: date-time
             * @description When it stops working. There is nothing to renew it with.
             */
            expiresAt: string;
            /**
             * Format: uuid
             * @description The grant this token acts under.
             */
            operatorId: string;
            /**
             * @description The platform permissions the operator holds, for the client to shape its own navigation.
             *     Advisory: every one is re-checked server-side on the request that uses it.
             */
            permissions: string[];
        };
        ProblemDetails: {
            detail?: null | string;
            instance?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            title?: null | string;
            type?: null | string;
        };
        RefreshRequest: {
            /** @description Native clients only; web clients send the cookie. */
            refreshHandle: null | string;
        };
        RegisterRequest: {
            /** @description Whether the aydınlatma metni was acknowledged. */
            acceptedKvkkNotice: boolean;
            /** @description Web or native, deciding where the refresh handle goes. */
            clientKind?: components["schemas"]["SessionClientKind"];
            /** @description Their address. */
            email: string;
            /** @description The owner's name. */
            fullName: string;
            /** @description The studio's name. */
            organizationName: string;
            /** @description Checked against the policy before anything is written. */
            password: string;
        };
        ResendVerificationRequest: {
            /** @description The address to re-send to. */
            email: string;
        };
        ResetPasswordRequest: {
            /** @description The new password. Checked against the policy. */
            password: string;
            /** @description The handle from the reset link. */
            token: string;
        };
        /**
         * @description Where a session is being used from. Decides how the refresh handle is carried.
         * @default Web
         * @enum {unknown}
         */
        SessionClientKind: "Web" | "Native";
        /**
         * @description A role held by a staff member <i>within an organization</i>.
         * @enum {unknown}
         */
        StaffRole: "OrganizationManager" | "SalesFinanceConsultant" | "Coach";
        /**
         * @description A staff member's state on the roster.
         * @enum {unknown}
         */
        StaffStatus: "Active" | "OnLeave" | "Inactive" | "Invited";
        /** @description One break-glass event, with the studio it was opened against. */
        SupportAuditEvent: {
            /** @description The audit row. */
            event: components["schemas"]["AuditEventSummary"];
            /**
             * Format: uuid
             * @description Which studio. Never null for this action.
             */
            organizationId: string;
        };
        /** @description What a break-glass session reads about one studio. */
        SupportOrganizationSnapshot: {
            /**
             * Format: date-time
             * @description When it registered.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When deletion was requested, or null.
             */
            deletionRequestedAt: null | string;
            /** @description Its BCP 47 locale. */
            locale: string;
            /** @description Its name. */
            name: string;
            /**
             * Format: uuid
             * @description The studio.
             */
            organizationId: string;
            /** @description Its URL-safe identifier. */
            slug: string;
            /** @description Its roster. */
            staff: components["schemas"]["SupportStaffMember"][];
            /** @description Its lifecycle state. */
            status: string;
            /** @description Its IANA time zone. */
            timeZoneId: string;
        };
        /** @description One roster row, as a support session sees it. */
        SupportStaffMember: {
            /** @description Their address, which is how a support conversation identifies them. */
            email: string;
            /** @description Their name. */
            fullName: string;
            /** @description Whether they are the studio's owner. */
            isOwner: boolean;
            /** @description Their role, as a wire enum name. */
            role: string;
            /**
             * Format: uuid
             * @description The assignment key (ADR-0016).
             */
            staffMemberId: string;
            /** @description Their roster state. */
            status: string;
            /**
             * Format: uuid
             * @description Their account, or null if they have not accepted an invitation yet.
             */
            userId: null | string;
        };
        VerifyEmailRequest: {
            /** @description The handle from the verification link. */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description No token, an expired one, a revoked session, or a stale permission version. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RequestOrganizationDeletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RequestOrganizationExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListPendingInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingInvitation"][];
                };
            };
            /** @description No token, an expired one, a revoked session, or a stale permission version. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    InviteStaffMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteStaffMemberBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description No token, an expired one, a revoked session, or a stale permission version. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RevokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No token, an expired one, a revoked session, or a stale permission version. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ResendInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description No token, an expired one, a revoked session, or a stale permission version. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description An RFC 9457 problem document. `code` is stable and is what clients branch on. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
